const vocabularyData = [
  {
    "No.": 1,
    "語彙 (Từ vựng)": "ミルク",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Sữa",
  },
  {
    "No.": 2,
    "語彙 (Từ vựng)": "ケーキ",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Bánh ngọt",
  },
  {
    "No.": 3,
    "語彙 (Từ vựng)": "ピアノ",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Đàn piano",
  },
  {
    "No.": 4,
    "語彙 (Từ vựng)": "パソコン",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Máy tính cá nhân",
  },
  {
    "No.": 5,
    "語彙 (Từ vựng)": "メンバー",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Thành viên",
  },
  {
    "No.": 6,
    "語彙 (Từ vựng)": "エンジニア",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Kỹ sư",
  },
  {
    "No.": 7,
    "語彙 (Từ vựng)": "ビール",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Bia",
  },
  {
    "No.": 8,
    "語彙 (Từ vựng)": "レンタカー",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Xe thuê",
  },
  {
    "No.": 9,
    "語彙 (Từ vựng)": "テント",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Lều",
  },
  {
    "No.": 10,
    "語彙 (Từ vựng)": "カラオケ",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Karaoke",
  },
  {
    "No.": 11,
    "語彙 (Từ vựng)": "ライブハウス",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Nhà hát biểu diễn nhạc sống",
  },
  {
    "No.": 12,
    "語彙 (Từ vựng)": "プリンター",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Máy in",
  },
  {
    "No.": 13,
    "語彙 (Từ vựng)": "ズボン",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Quần dài",
  },
  {
    "No.": 14,
    "語彙 (Từ vựng)": "スニーカー",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Giày thể thao",
  },
  {
    "No.": 15,
    "語彙 (Từ vựng)": "ペース",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Nhịp độ",
  },
  {
    "No.": 16,
    "語彙 (Từ vựng)": "ゴミ",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Rác",
  },
  {
    "No.": 17,
    "語彙 (Từ vựng)": "ルール",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Quy tắc",
  },
  {
    "No.": 18,
    "語彙 (Từ vựng)": "ドア",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Cửa",
  },
  {
    "No.": 19,
    "語彙 (Từ vựng)": "エアコン",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Máy điều hòa",
  },
  {
    "No.": 20,
    "語彙 (Từ vựng)": "シャンプー",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Dầu gội",
  },
  {
    "No.": 21,
    "語彙 (Từ vựng)": "ティッシュペーパー",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Giấy lau, giấy ăn",
  },
  {
    "No.": 22,
    "語彙 (Từ vựng)": "シラバス",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Nội dung môn học, đề cương",
  },
  {
    "No.": 23,
    "語彙 (Từ vựng)": "テスト",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Bài kiểm tra",
  },
  {
    "No.": 24,
    "語彙 (Từ vựng)": "レポート",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Bản báo cáo",
  },
  {
    "No.": 25,
    "語彙 (Từ vựng)": "じゅぎょう",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Tiết học",
  },
  {
    "No.": 26,
    "語彙 (Từ vựng)": "マフラー",
    "漢字 (Chữ Hán)": "",
    "意味 (Ý nghĩa)": "Khăn quàng cổ",
  },
  {
    "No.": 27,
    "語彙 (Từ vựng)": "やきん",
    "漢字 (Chữ Hán)": "夜勤",
    "意味 (Ý nghĩa)": "Ca đêm",
  },
  {
    "No.": 28,
    "語彙 (Từ vựng)": "じっか",
    "漢字 (Chữ Hán)": "実家",
    "意味 (Ý nghĩa)": "Nhà bố mẹ đẻ",
  },
  {
    "No.": 29,
    "語彙 (Từ vựng)": "いんたい",
    "漢字 (Chữ Hán)": "引退",
    "意味 (Ý nghĩa)": "Nghỉ hưu, giải nghệ",
  },
  {
    "No.": 30,
    "語彙 (Từ vựng)": "かじ",
    "漢字 (Chữ Hán)": "家事",
    "意味 (Ý nghĩa)": "Việc nhà",
  },
  {
    "No.": 31,
    "語彙 (Từ vựng)": "おしゃべり",
    "漢字 (Chữ Hán)": "お喋り",
    "意味 (Ý nghĩa)": "Nói chuyện, tán gẫu",
  },
  {
    "No.": 32,
    "語彙 (Từ vựng)": "きんじょ",
    "漢字 (Chữ Hán)": "近所",
    "意味 (Ý nghĩa)": "Hàng xóm, khu vực gần nhà",
  },
  {
    "No.": 33,
    "語彙 (Từ vựng)": "しょうかい",
    "漢字 (Chữ Hán)": "紹介",
    "意味 (Ý nghĩa)": "Giới thiệu",
  },
  {
    "No.": 34,
    "語彙 (Từ vựng)": "わすれます",
    "漢字 (Chữ Hán)": "忘れます",
    "意味 (Ý nghĩa)": "Quên",
  },
  {
    "No.": 35,
    "語彙 (Từ vựng)": "くらします",
    "漢字 (Chữ Hán)": "暮らします",
    "意味 (Ý nghĩa)": "Sinh sống",
  },
  {
    "No.": 36,
    "語彙 (Từ vựng)": "うまれます",
    "漢字 (Chữ Hán)": "生まれます",
    "意味 (Ý nghĩa)": "Được sinh ra",
  },
  {
    "No.": 37,
    "語彙 (Từ vựng)": "なきます",
    "漢字 (Chữ Hán)": "泣きます",
    "意味 (Ý nghĩa)": "Khóc",
  },
  {
    "No.": 38,
    "語彙 (Từ vựng)": "わらいます",
    "漢字 (Chữ Hán)": "笑います",
    "意味 (Ý nghĩa)": "Cười",
  },
  {
    "No.": 39,
    "語彙 (Từ vựng)": "えいぎょうします",
    "漢字 (Chữ Hán)": "営業します",
    "意味 (Ý nghĩa)": "Kinh doanh, quản lý",
  },
  {
    "No.": 40,
    "語彙 (Từ vựng)": "たてもの",
    "漢字 (Chữ Hán)": "建物",
    "意味 (Ý nghĩa)": "Tòa nhà",
  },
  {
    "No.": 41,
    "語彙 (Từ vựng)": "しんせん",
    "漢字 (Chữ Hán)": "新鮮",
    "意味 (Ý nghĩa)": "Tươi mới",
  },
  {
    "No.": 42,
    "語彙 (Từ vựng)": "プロジェクト",
    "漢字 (Chữ Hán)": "プロジェクト",
    "意味 (Ý nghĩa)": "Dự án",
  },
  {
    "No.": 43,
    "語彙 (Từ vựng)": "タスク",
    "漢字 (Chữ Hán)": "タスク",
    "意味 (Ý nghĩa)": "Công việc, nhiệm vụ",
  },
  {
    "No.": 44,
    "語彙 (Từ vựng)": "カンバン",
    "漢字 (Chữ Hán)": "カンバン",
    "意味 (Ý nghĩa)": "Bảng Kanban",
  },
  {
    "No.": 45,
    "語彙 (Từ vựng)": "バックログ",
    "漢字 (Chữ Hán)": "バックログ",
    "意味 (Ý nghĩa)": "Backlog (danh sách công việc tồn đọng)",
  },
  {
    "No.": 46,
    "語彙 (Từ vựng)": "かくにん",
    "漢字 (Chữ Hán)": "確認",
    "意味 (Ý nghĩa)": "Xác nhận",
  },
  {
    "No.": 47,
    "語彙 (Từ vựng)": "かだい",
    "漢字 (Chữ Hán)": "課題",
    "意味 (Ý nghĩa)": "Vấn đề, nhiệm vụ",
  },
  {
    "No.": 48,
    "語彙 (Từ vựng)": "たんとう",
    "漢字 (Chữ Hán)": "担当",
    "意味 (Ý nghĩa)": "Phụ trách",
  },
  {
    "No.": 49,
    "語彙 (Từ vựng)": "しんちょくじょうきょう",
    "漢字 (Chữ Hán)": "進捗状況",
    "意味 (Ý nghĩa)": "Tình trạng tiến độ",
  },
  {
    "No.": 50,
    "語彙 (Từ vựng)": "あさかい",
    "漢字 (Chữ Hán)": "朝会",
    "意味 (Ý nghĩa)": "Cuộc họp buổi sáng",
  },
  {
    "No.": 51,
    "語彙 (Từ vựng)": "ていあんします",
    "漢字 (Chữ Hán)": "提案します",
    "意味 (Ý nghĩa)": "Tiến hành, tổ chức",
  },
  {
    "No.": 52,
    "語彙 (Từ vựng)": "いどうします",
    "漢字 (Chữ Hán)": "移動します",
    "意味 (Ý nghĩa)": "Di chuyển",
  },
  {
    "No.": 53,
    "語彙 (Từ vựng)": "かいけつ",
    "漢字 (Chữ Hán)": "解決",
    "意味 (Ý nghĩa)": "Giải quyết",
  },
  {
    "No.": 54,
    "語彙 (Từ vựng)": "しめきり",
    "漢字 (Chữ Hán)": "締切",
    "意味 (Ý nghĩa)": "Hạn chót",
  },
  {
    "No.": 55,
    "語彙 (Từ vựng)": "インターネット",
    "漢字 (Chữ Hán)": "インターネット",
    "意味 (Ý nghĩa)": "Internet",
  },
  {
    "No.": 56,
    "語彙 (Từ vựng)": "すすみます",
    "漢字 (Chữ Hán)": "進みます",
    "意味 (Ý nghĩa)": "Tiến triển",
  },
];

// Process the data for use in the application
function processVocabularyData() {
  return vocabularyData.map((item) => {
    return {
      id: item["No."] || 0,
      vocabulary: item["語彙 (Từ vựng)"] || "",
      kanji: item["漢字 (Chữ Hán)"] || "",
      meaning: item["意味 (Ý nghĩa)"] || "",
    };
  });
}

// Make the processed data available to the main script
const flashcardData = processVocabularyData();
